import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  en('English', 'en'),
  pt('Português', 'pt'),
  es('Español', 'es');

  const AppLanguage(this.label, this.code);

  final String label;
  final String code;

  static AppLanguage fromCode(String? code) => AppLanguage.values.firstWhere(
        (language) => language.code == code,
        orElse: () => AppLanguage.pt,
      );
}

final appLanguageControllerProvider =
    StateNotifierProvider<AppLanguageController, AppLanguage>(
  (ref) => AppLanguageController()..load(),
);

final class AppLanguageController extends StateNotifier<AppLanguage> {
  AppLanguageController() : super(AppLanguage.pt);

  static const _key = 'field_time_language';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    state = AppLanguage.fromCode(prefs.getString(_key));
  }

  Future<void> setLanguage(AppLanguage language) async {
    state = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, language.code);
  }
}

final class AppStrings {
  const AppStrings(this.language);

  final AppLanguage language;

  String t(String key, [Map<String, Object?> values = const {}]) {
    final selected = _strings[language]?[key];
    final fallback = _strings[AppLanguage.en]?[key];
    final template = selected?.trim().isNotEmpty == true
        ? selected!
        : fallback?.trim().isNotEmpty == true
            ? fallback!
            : _fallbackHumanText(key);
    return _replaceValues(template, values);
  }
}

extension AppStringsContext on BuildContext {
  AppLanguage get appLanguage => ProviderScope.containerOf(this, listen: true)
      .read(appLanguageControllerProvider);

  AppStrings get appStrings => AppStrings(appLanguage);

  String tr(String key, [Map<String, Object?> values = const {}]) =>
      appStrings.t(key, values);
}

String _replaceValues(String template, Map<String, Object?> values) {
  var result = template;
  for (final entry in values.entries) {
    result = result.replaceAll('{${entry.key}}', entry.value?.toString() ?? '');
  }
  return result;
}

String _fallbackHumanText(String key) {
  final words = key
      .replaceAll(RegExp(r'[_\-.]+'), ' ')
      .replaceAllMapped(RegExp(r'([a-z])([A-Z])'), (match) {
    return '${match.group(1)} ${match.group(2)}';
  }).trim();
  if (words.isEmpty) return 'Field Time';
  return '${words[0].toUpperCase()}${words.substring(1)}';
}

const _strings = {
  AppLanguage.en: {
    'app.title': 'Field Time',
    'brand.byDeveloper': 'by JKDD TECH',
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.done': 'Done',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.pending': 'Pending',
    'common.open': 'Open',
    'common.unavailable': 'Unavailable',
    'common.none': 'None',
    'common.localExcel': 'Local Excel',
    'common.comingSoon': 'Coming Soon',
    'common.systemDefault': 'System default',
    'common.landscape': 'Landscape',
    'common.portrait': 'Portrait',
    'common.letter': 'Letter',
    'common.us': 'U.S.',
    'common.recordsCount': '{count} records',
    'common.receiptsTotal': '{count} receipts - {total} total',
    'common.peopleCount': '{count} people',
    'common.peopleScheduled': '{count} people scheduled',
    'common.peopleWorking': '{count} working',
    'common.noEntryCount': '{count} without clock-in',
    'common.all': 'All',
    'common.details': 'Details',
    'common.discard': 'Discard',
    'common.saveChanges': 'Save changes',
    'common.registrationNumber': 'Registration Number',
    'common.generatedAutomatically': 'Generated automatically',
    'auth.testEnvironment': 'TEST ENVIRONMENT',
    'auth.username': 'E-mail or user',
    'auth.password': 'Password',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.logoutHelp': 'End the current local test session',
    'auth.logoutConfirm':
        'Do you want to logout and return to the login screen?',
    'auth.invalidCredentials': 'Invalid user or password.',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'auth.roleCollaborator': 'Collaborator',
    'auth.roleSupervisor': 'Supervisor',
    'auth.roleDirector': 'Director',
    'maps.openNavigation': 'Open navigation',
    'maps.navigate': 'Navigate',
    'maps.routeToJob': 'Route to Job',
    'maps.chooseApp': 'Choose a map app',
    'maps.openWaze': 'Open in Waze',
    'maps.openGoogleMaps': 'Open in Google Maps',
    'maps.openAppleMaps': 'Open in Apple Maps',
    'jobs.payPremium': 'Pay Premium',
    'jobs.noPayPremium': 'No Pay Premium',
    'jobs.travelBonusValue': 'Travel Bonus {hours}',
    'jobs.payPremiumValue': 'Pay Premium {value}',
    'timesheet.generateTimesheet': 'Generate Timesheet',
    'timesheet.payPremium': 'Pay Premium',
    'employees.setInactive': 'Set Inactive',
    'employees.setActive': 'Set Active',
    'employees.confirmInactive': 'Do you want to deactivate this employee?',
    'employees.confirmActive': 'Do you want to reactivate this employee?',
    'employees.statusSaved': 'Employee status saved.',
    'profiles.saveCurrent':
        'Do you want to save this profile as the current test profile?',
    'supervisor.president': 'President',
    'supervisor.director': 'Director',
    'supervisor.hoursApprovedSuccess': 'Hours approved successfully.',
    'supervisor.hoursRejectedSuccess': 'Hours rejected successfully.',
    'supervisor.correctionRequestedSuccess':
        'Correction requested successfully.',
    'supervisor.cannotReviewOwnTime':
        'You cannot approve or reject your own time records.',
    'supervisor.travelBonusUpdatedSuccess':
        'Travel Bonus updated successfully.',
    'timesheet.generatedSuccess': 'Timesheet generated successfully.',
    'timesheet.generationError': 'Timesheet could not be generated.',
    'timesheet.noRecordsForPeriod':
        'No time records were found for this period.',
    'fieldTime.localDataLoaded': 'Local data loaded.',
    'fieldTime.clockInProgress': 'Clocking in...',
    'fieldTime.clockInSuccess': 'Clock-in registered for {job}.',
    'fieldTime.switchJobProgress': 'Switching job...',
    'fieldTime.switchJobSuccess': 'New period started for {job}.',
    'fieldTime.endDayProgress': 'Ending workday...',
    'fieldTime.endDaySuccess': 'Workday ended successfully.',
    'fieldTime.savePhotoProgress': 'Saving photo...',
    'fieldTime.photoLinked': 'Photo linked to job {job}.',
    'fieldTime.saveReceiptProgress': 'Saving receipt...',
    'fieldTime.reimbursementSubmitted': 'Reimbursement sent for approval.',
    'fieldTime.draftSaved': 'Draft saved.',
    'fieldTime.saveObservationProgress': 'Saving note...',
    'fieldTime.observationAdded': 'Note added to the current period.',
    'fieldTime.operationFailed': 'The operation could not be completed.',
    'fieldTime.deviceSaveFailed': 'Data could not be saved on this device.',
    'fieldTime.openPeriodExists': 'There is already an open period.',
    'fieldTime.clockInBeforeSwitchJob': 'Clock in before switching jobs.',
    'fieldTime.selectDifferentJob': 'Select a different job.',
    'fieldTime.invalidSwitchTime': 'Invalid switch time.',
    'fieldTime.noOpenWorkday': 'There is no open workday.',
    'fieldTime.invalidClockOutTime': 'Invalid clock-out time.',
    'fieldTime.confirmReceiptBeforeSubmit':
        'Review and confirm the data before submitting.',
    'fieldTime.invalidReceiptFields':
        'Fill in merchant, description and amount correctly.',
    'fieldTime.duplicateRegistration':
        'Duplicate UUID or registration number. Record was not saved.',
    'fieldTime.clockInBeforeObservation': 'Clock in before adding notes.',
    'fieldTime.typeObservation': 'Type a note.',
    'nav.home': 'Home',
    'nav.timesheet': 'Timesheet',
    'nav.jobs': 'Jobs',
    'nav.receipts': 'Receipts',
    'nav.employees': 'Employees',
    'nav.management': 'Management',
    'nav.menu': 'Menu',
    'home.dailySummary': 'Daily summary',
    'home.hoursWorked': 'Hours worked',
    'home.bonusHours': 'Bonus hours',
    'home.jobsVisited': 'Jobs visited',
    'home.receipts': 'Receipts',
    'home.reimbursements': 'Reimbursements',
    'home.pendingSync': 'Pending sync',
    'home.goodMorning': 'Good morning',
    'home.goodAfternoon': 'Good afternoon',
    'home.goodEvening': 'Good evening',
    'home.workdayInProgress': 'Workday in progress',
    'home.readyToClockIn': 'Ready to clock in',
    'home.clockedIn': 'Clocked in',
    'home.clockedOut': 'Clocked out',
    'home.online': 'Online',
    'home.offline': 'Offline',
    'home.pendingItems': '{count} pending',
    'home.currentStatus': 'Current status',
    'home.currentStatusSubtitle': 'Live field activity overview',
    'home.noActiveJob': 'No active job',
    'home.selectJobWhenClockingIn': 'Select a job when clocking in.',
    'home.clockInTime': 'Clock-in time',
    'home.workedTime': 'Worked time',
    'home.gps': 'GPS',
    'home.clientCompany': 'Client company',
    'home.subcontractor': 'Subcontractor',
    'home.currentNote': 'Current note',
    'home.primaryAction': 'Primary action',
    'home.secondaryActions': 'Secondary actions',
    'home.clockIn': 'CLOCK IN',
    'home.endWorkday': 'END WORKDAY',
    'home.switchJob': 'Switch Job',
    'home.attachReceipt': 'Attach Receipt',
    'home.requestReimbursement': 'Request Reimbursement',
    'home.addPhoto': 'Add Photo',
    'home.addNote': 'Add Note',
    'home.myTimesheet': 'My Timesheet',
    'home.todayTimesheet': "Today's timesheet",
    'home.todayTimeline': 'Timeline of work periods for this device.',
    'home.noWorkPeriods': 'No work periods yet',
    'home.noWorkPeriodsHelp': "Clock in to start building today's timesheet.",
    'home.receiptsAndReimbursements': 'Receipts and reimbursements',
    'home.noReceiptsYet': 'No receipts yet',
    'home.noReceiptsYetHelp':
        'Attach a receipt when a job expense needs reimbursement.',
    'home.excellentWorkday': 'Have an excellent workday',
    'home.workSafely': 'Work safely',
    'home.goodRest': 'Have a good rest',
    'endDay.title': 'End workday?',
    'endDay.message':
        'Are you sure you want to end the workday? The current work period will be closed with the current time and GPS status.',
    'endDay.confirm': 'Yes, end workday',
    'endDay.success': 'Workday ended successfully',
    'endDay.rest': 'Have a good rest',
    'endDay.tomorrow': 'See you tomorrow',
    'endDay.summary': 'Workday summary',
    'endDay.firstClockIn': 'First clock-in',
    'endDay.lastClockOut': 'Last clock-out',
    'endDay.receiptsSubmitted': 'Receipts submitted',
    'endDay.weekHours': 'Week hours',
    'endDay.receiptQuestion':
        'Do you have receipts or documents to attach before closing the workday?',
    'endDay.attachNow': 'Attach now',
    'endDay.noReceipts': 'No receipts',
    'endDay.viewTimesheet': 'View My Timesheet',
    'photo.clockInRequired': 'Clock in before adding a job photo.',
    'photo.addPhoto': 'Add photo',
    'photo.takePhoto': 'Take photo',
    'photo.selectImage': 'Select image',
    'photo.cameraUnavailable':
        'Camera or photo library could not be opened on this device.',
    'note.clockInRequired': 'Clock in before adding notes.',
    'note.currentPeriod': 'Current period note',
    'note.hint': 'Type a note',
    'jobs.title': 'Jobs',
    'jobs.subtitle': 'Visual directory of available Field Time jobs.',
    'jobs.search': 'Search',
    'jobs.active': 'Active',
    'jobs.inactive': 'Inactive',
    'jobs.address': 'Address',
    'jobs.city': 'City',
    'jobs.state': 'State',
    'jobs.zipCode': 'ZIP Code',
    'jobs.status': 'Status',
    'jobs.noJobsFound': 'No jobs found',
    'jobs.noJobsAvailable': 'No jobs available',
    'jobs.noJobsAvailableHelp':
        'Import jobs from data_import/input before clocking in.',
    'jobs.selectJob': 'Select job',
    'jobs.selectJobForClockIn': 'Select job for clock-in',
    'jobs.switchToWhichJob': 'Switch to which job?',
    'jobs.currentJob': 'Current job',
    'jobs.openJob': 'Open Job',
    'jobs.viewJob': 'View Job',
    'jobs.newJob': 'New Job',
    'jobs.jobNumber': 'Job number',
    'jobs.jobName': 'Job name',
    'jobs.allowSupervisorCreateJobs': 'Allow Supervisor to create jobs',
    'jobs.fixedTeamsDisabled': 'No fixed teams: allocation by date and job.',
    'jobs.listTitle': 'Job list',
    'jobs.all': 'All jobs',
    'jobs.withBonus': 'With bonus',
    'jobs.details': 'Job Details',
    'jobs.client': 'Client',
    'jobs.supervisor': 'Supervisor',
    'jobs.travelBonus': 'Travel Bonus',
    'jobs.accessInstructions': 'Access instructions',
    'jobs.location': 'Location',
    'jobs.selectThisJob': 'Select job',
    'jobs.openMap': 'Open map',
    'jobs.newJobRequest': 'Request new job',
    'jobs.newJobAdmin': '+ Register New Job',
    'jobs.pendingRequest': 'Request pending',
    'jobs.duplicateWarning': 'Possible duplicate job number or address.',
    'jobs.requestPrepared': 'New job request prepared for supervisor review.',
    'employees.management': 'Employee Management',
    'employees.subtitle':
        'Imported employee directory for Field Time operations.',
    'employees.add': '+ Add Employee',
    'employees.edit': 'Edit employee',
    'employees.deactivate': 'Deactivate employee',
    'employees.delete': 'Delete employee',
    'employees.deleteBlocked': 'Employees with history cannot be deleted.',
    'employees.details': 'Employee details',
    'employees.search': 'Search by name or Employee ID',
    'employees.status': 'Status',
    'employees.activeStatus': 'Active',
    'employees.inactiveStatus': 'Inactive',
    'employees.company': 'Company',
    'employees.category': 'Category',
    'employees.supervisor': 'Supervisor',
    'employees.role': 'Function',
    'employees.all': 'All',
    'employees.noneFound': 'No employees found',
    'employees.noneFoundHelp':
        'Adjust the search or filters to find employees.',
    'employees.unavailable': 'Employee database unavailable',
    'employees.loadError':
        'The employees file is missing or invalid. Check assets/data/employees.json.',
    'employees.employeeId': 'Employee ID',
    'employees.name': 'Name',
    'employees.phone': 'Phone',
    'employees.email': 'Email',
    'employees.address': 'Address',
    'employees.emergencyContact': 'Emergency contact',
    'employees.notes': 'Notes',
    'employees.required': 'Required field',
    'timesheet.title': 'Timesheet',
    'timesheet.subtitle': 'Review hours, jobs, receipts and export readiness.',
    'timesheet.generatePdf': 'Generate PDF',
    'timesheet.previewPdf': 'Preview PDF',
    'timesheet.share': 'Share',
    'timesheet.download': 'Download',
    'timesheet.period': 'Period',
    'timesheet.today': 'Today',
    'timesheet.week': 'Week',
    'timesheet.month': 'Month',
    'timesheet.year': 'Year',
    'timesheet.dailyRecords': 'Daily records',
    'timesheet.noRecords': 'No information found',
    'timesheet.noRecordsHelp': 'Clocked work periods will appear here.',
    'timesheet.regularHours': 'Regular hours',
    'timesheet.bonusHours': 'Bonus hours',
    'timesheet.totalHours': 'Total hours',
    'timesheet.totalByJob': 'Total by job',
    'timesheet.jobs': 'Jobs',
    'timesheet.receipts': 'Receipts',
    'timesheet.reimbursements': 'Reimbursements',
    'timesheet.date': 'Date',
    'timesheet.job': 'Job',
    'timesheet.name': 'Name',
    'timesheet.address': 'Address',
    'timesheet.clockIn': 'Clock In',
    'timesheet.clockOut': 'Clock Out',
    'timesheet.duration': 'Duration',
    'timesheet.hours': 'Hours',
    'timesheet.bonus': 'Bonus',
    'timesheet.total': 'Total',
    'timesheet.approval': 'Approval',
    'timesheet.notes': 'Notes',
    'timesheet.inProgress': 'In progress',
    'timesheet.fileName': 'field_time_timesheet.pdf',
    'timesheet.travelBonusLine': 'Travel Bonus',
    'timesheet.totalWorkedHours': 'Total Worked Hours',
    'timesheet.totalTravelBonus': 'Total Travel Bonus',
    'timesheet.grandTotal': 'Grand Total',
    'pdf.title': 'Field Time Timesheet',
    'pdf.totalGeneral': 'Grand total: {total}',
    'pdf.totalWorkedHours': 'Total worked hours: {total}',
    'pdf.totalTravelBonus': 'Total travel bonus: {total}',
    'pdf.receiptsSummary': 'Receipt summary',
    'pdf.noLinkedReceipts': 'No receipt linked to a job this week.',
    'pdf.worker': 'Worker: {worker}',
    'pdf.contractor': 'Contractor: {contractor}',
    'pdf.subcontractor': 'Subcontractor: {subcontractor}',
    'pdf.responsible': 'Responsible: {worker}',
    'pdf.period': 'Period: {start} to {end}',
    'pdf.week': 'Week: Monday to Sunday',
    'pdf.noRecords': 'No records',
    'pdf.receipt': 'Receipt - {merchant}',
    'receipts.title': 'Receipts',
    'receipts.andReimbursements': 'Receipts and reimbursements',
    'receipts.addReceipt': 'Add receipt',
    'receipts.attachReceipt': 'Attach Receipt',
    'receipts.camera': 'Camera',
    'receipts.gallery': 'Gallery',
    'receipts.takePhoto': 'Take photo',
    'receipts.selectImage': 'Select image',
    'receipts.merchant': 'Merchant',
    'receipts.date': 'Date',
    'receipts.amount': 'Amount',
    'receipts.tax': 'Tax',
    'receipts.receiptNumber': 'Receipt number',
    'receipts.description': 'Description',
    'receipts.category': 'Category',
    'receipts.observation': 'Observation',
    'receipts.notes': 'Notes',
    'receipts.submit': 'Submit',
    'receipts.send': 'Send',
    'receipts.saveDraft': 'Save draft',
    'receipts.file': 'File: {name}',
    'receipts.reviewConfirm': 'I reviewed and confirm the information',
    'receipts.mockNotice':
        'Automatic receipt reading is prepared, but still uses mock mode. No data will be invented: review, correct and confirm before sending.',
    'receipts.automaticReadingNotIntegrated':
        'Automated receipt reading is not integrated yet. Review and fill in the fields.',
    'receipts.noReceiptsDevice': 'No receipts on this device',
    'receipts.noReceiptsDeviceHelp':
        'Use Attach Receipt to capture an expense and request reimbursement.',
    'receipts.cameraUnavailable':
        'Camera or photo library could not be opened.',
    'receipts.attachPhotoRequired': 'Attach a receipt photo or image.',
    'receipts.requiredField': 'Required field',
    'receipts.invalidAmount': 'Invalid amount',
    'receiptStatus.draft': 'Draft',
    'receiptStatus.submitted': 'Submitted',
    'receiptStatus.underReview': 'Under review',
    'receiptStatus.approved': 'Approved',
    'receiptStatus.rejected': 'Rejected',
    'receiptStatus.paid': 'Paid',
    'settings.title': 'Settings',
    'settings.subtitle': 'Profile, pilot controls and app preferences.',
    'settings.preferences': 'Preferences',
    'settings.language': 'Language',
    'settings.languageHelp': 'Choose the app language.',
    'settings.saved': 'Language saved.',
    'settings.unsavedChanges': 'Unsaved changes',
    'settings.unsavedDialogTitle': 'Settings changed',
    'settings.unsavedDialogMessage':
        'You have unsaved settings changes. What do you want to do before leaving?',
    'settings.discarded': 'Changes discarded.',
    'settings.draftRecovered': 'A settings draft is available for review.',
    'settings.data': 'Data',
    'settings.account': 'Account',
    'settings.profile': 'Profile',
    'settings.company': 'Company',
    'settings.permissions': 'Permissions',
    'settings.theme': 'Theme',
    'settings.dateFormat': 'Date format',
    'settings.dateFormatValue': 'MM/DD/YYYY',
    'settings.timeFormat': 'Time format',
    'settings.timeFormatValue': '12-hour',
    'settings.units': 'Measurement units',
    'settings.reports': 'Reports',
    'settings.timesheetFormat': 'Timesheet format',
    'settings.paperSize': 'Paper size',
    'settings.defaultPaperSize': 'Default paper size',
    'settings.orientation': 'Orientation',
    'settings.pdfOrientation': 'PDF orientation',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.privacy': 'Privacy',
    'settings.terms': 'Terms',
    'settings.restoreDefault': 'Restore default',
    'settings.landscapePlanned': 'Landscape planned',
    'import.title': 'Job Import',
    'import.subtitle': 'Local job database for Field Time. Works offline.',
    'import.updateJobs': 'Update Jobs',
    'import.viewReport': 'View Report',
    'import.lastUpdate': 'Last update',
    'import.lastFile': 'Last processed file',
    'import.jobsCount': 'Job count',
    'import.errorCount': 'Error count',
    'import.processedFile': 'Processed file',
    'import.noSpreadsheet': 'No spreadsheet found',
    'import.noFileProcessed': 'No file processed',
    'import.pending': 'Pending',
    'import.summary': 'Summary',
    'import.databaseUnavailable': 'Jobs database unavailable',
    'import.loadError':
        'The jobs file is missing or invalid. Reimport the Excel file and check JOBS_IMPORT_REPORT.md.',
    'import.reviewReport':
        'Review the report before using the database in the field.',
    'import.updateInstructions':
        'Replace the updated spreadsheet in data_import/input/ and run dart run tool/import_jobs_from_excel.dart. Remote upload was not implemented in this step.',
    'import.reportTitle': 'Import Report',
    'import.reportInstructions':
        'The local report is generated at data_import/reports/JOBS_IMPORT_REPORT.md.',
    'approval.approve': 'Approve',
    'approval.reject': 'Reject',
    'approval.review': 'Review',
    'approval.pending': 'Pending',
    'approval.approved': 'Approved',
    'approval.rejected': 'Rejected',
    'approval.underReview': 'Under review',
    'approval.corrected': 'Corrected',
    'approval.resubmitted': 'Resubmitted',
    'approval.correctionRequested': 'Correction requested',
    'approval.closed': 'Closed',
    'approval.working': 'Working',
    'approval.reason': 'Reason',
    'approval.observation': 'Observation',
    'approval.confirmation': 'Confirmation',
    'approval.history': 'History',
    'approval.approvedBy': 'Approved by',
    'approval.rejectedBy': 'Rejected by',
    'approval.reviewedBy': 'Reviewed by',
    'approval.confirmApprove': 'Approve this time record?',
    'approval.confirmReject': 'Reject this time record?',
    'approval.approveMessage':
        'The record will be marked as Approved, locked from common edits and released to Timesheet and reports.',
    'approval.rejectMessage':
        'The record will be returned to the worker with the reason provided.',
    'approval.confirmApproveTitle': 'Confirm approval',
    'approval.approvalObservation': 'Approval observation',
    'approval.rejectRecord': 'Reject record',
    'approval.rejectionReasonRequired': 'Required rejection reason',
    'approval.reviewRecord': 'Review record',
    'approval.reviewRequest': 'Correction or review requested',
    'approval.additionalObservations': 'Additional observations',
    'approval.sendToReview': 'Send for review',
    'approval.reviewEntry': 'Review entry',
    'approval.clockIn': 'Clock in',
    'approval.clockOut': 'Clock out',
    'approval.breakMinutes': 'Break min',
    'approval.travelBonus': 'Travel Bonus',
    'approval.requiredJustification': 'Required justification',
    'approval.saveReview': 'Save review',
    'approval.approveAll': 'Approve all',
    'approval.approveAllValid': 'Approve all valid',
    'approval.noSubmittedRecords': 'No submitted records',
    'approval.noSubmittedRecordsHelp':
        'Pending Employee and Contractor records appear here.',
    'supervisor.title': 'Supervisor Center',
    'supervisor.management': 'Management',
    'supervisor.approveTime': 'Approve Time',
    'supervisor.schedule': 'Schedule',
    'supervisor.jobs': 'Jobs',
    'supervisor.peopleByJob': 'People by Job',
    'supervisor.workingNow': 'Working Now',
    'supervisor.pilotMode': 'pilot mode',
    'supervisor.managementUnavailable': 'Management unavailable',
    'supervisor.clockInSimulated': 'Clock-in simulated in pilot.',
    'supervisor.breakStarted': 'Break started in pilot.',
    'supervisor.breakEnded': 'Break ended in pilot.',
    'supervisor.hoursSent': 'Hours sent.',
    'supervisor.roleChanged': 'Test mode changed.',
    'supervisor.createJobsAllowed': 'Supervisor can create jobs in the pilot.',
    'supervisor.createJobsBlocked': 'Supervisor job creation is blocked.',
    'supervisor.jobCreated': 'New job created in the pilot.',
    'supervisor.jobUpdated': 'Job updated.',
    'supervisor.employeeOrContractorOnly':
        'Only Employee or Contractor profiles can submit hours.',
    'supervisor.hoursCorrectedResubmitted':
        'Hours corrected and resubmitted for approval.',
    'supervisor.hoursSentForApproval': 'Hours sent for approval.',
    'supervisor.correctionReasonRequired': 'Enter the correction reason.',
    'supervisor.correctionSent': 'Correction sent for review.',
    'supervisor.entryApproved': 'Record approved.',
    'supervisor.entryRejected': 'Record rejected.',
    'supervisor.entrySentToReview': 'Record sent for review.',
    'supervisor.approvedRecordLocked':
        'Approved record is locked for regular edits.',
    'supervisor.changeJustificationRequired':
        'Every change requires a justification.',
    'supervisor.reviewSavedAudit': 'Review saved with audit log.',
    'supervisor.batchApproveJustificationRequired':
        'Enter a justification to approve in bulk.',
    'supervisor.validRecordsApproved': 'Valid records approved.',
    'supervisor.reviewJustificationRequired': 'Enter the review justification.',
    'supervisor.rejectionReasonRequired': 'Enter the rejection reason.',
    'supervisor.permissionDenied':
        'This profile does not have permission to perform this action.',
    'supervisor.noAssignedJob': 'No job is assigned to this employee.',
    'supervisor.testMode': 'Test mode',
    'supervisor.rbacUpdates':
        'The interface updates immediately according to RBAC.',
    'supervisor.pendingHours': 'Pending hours',
    'supervisor.approvedHours': 'Approved hours',
    'supervisor.rejectedHours': 'Rejected hours',
    'supervisor.activeJobs': 'Active jobs',
    'supervisor.openClockIns': 'Open clock-ins',
    'supervisor.reviewSubmittedRecords': 'Review submitted records',
    'supervisor.dailyRoute': 'Supervisor daily route',
    'supervisor.jobsAndDetails': 'Jobs and job details',
    'supervisor.dailyAllocation': 'Daily job allocation',
    'supervisor.today': 'Today',
    'supervisor.week': 'Week',
    'supervisor.calendar': 'Calendar',
    'supervisor.currentWorkerJob': "Today's job",
    'supervisor.workerJobSubtitle': 'My schedule, my hours and corrections.',
    'supervisor.noHoursSent': 'No hours sent',
    'supervisor.noHoursSentHelp':
        'Records for the current profile appear here.',
    'supervisor.requestCorrection': 'Request correction',
    'supervisor.correctionReason': 'Correction reason',
    'supervisor.observation': 'Observation',
    'supervisor.optionalNote': 'Optional note',
    'supervisor.employee': 'Employee',
    'supervisor.contractor': 'Contractor',
    'supervisor.owner': 'Owner',
    'supervisor.administrator': 'Administrator',
    'supervisor.coordinator': 'Coordinator',
    'supervisor.employeeNote': 'Employee note',
    'supervisor.supervisorNote': 'Supervisor note',
    'supervisor.rejectionReason': 'Rejection reason',
    'supervisor.reviewRequest': 'Review request',
    'supervisor.openRoute': 'Open Route',
    'supervisor.client': 'Client',
    'supervisor.supervisor': 'Supervisor',
    'supervisor.scheduledToday': 'Scheduled today',
    'supervisor.hoursToday': 'Hours today',
    'supervisor.peopleScheduled': 'People scheduled',
    'supervisor.peopleWorking': 'People working',
    'supervisor.withoutClockIn': 'Without clock-in',
    'supervisor.totalDayHours': 'Total day hours',
    'supervisor.peopleScheduledToday': 'People scheduled today',
    'supervisor.peopleWorkingNow': 'People working now',
    'supervisor.noChanges': 'No changes',
    'supervisor.noChangesHelp': 'Changes and approvals appear here.',
    'supervisor.jobInfo': 'Information',
    'supervisor.summary': 'Summary',
    'supervisor.peopleToday': 'People Today',
    'supervisor.hours': 'Hours',
    'supervisor.history': 'History',
    'supervisor.number': 'Number',
    'supervisor.startDate': 'Start date',
    'supervisor.scheduledTime': 'Scheduled time',
    'supervisor.editByPermission': 'Edit according to permission',
    'supervisor.visualEditEnabled': 'Visual editing enabled in pilot.',
    'supervisor.nobodyWorking': 'Nobody is working now',
    'supervisor.openEntriesAppear': 'Open clock-ins appear here.',
    'supervisor.viewRecord': 'View Record',
    'supervisor.viewJob': 'View Job',
    'supervisor.person': 'Person',
    'supervisor.role': 'Role',
    'supervisor.assignedBy': 'Assigned by',
    'supervisor.period': 'Period',
    'supervisor.status': 'Status',
    'supervisor.notes': 'Notes',
    'supervisor.job': 'Job',
    'supervisor.date': 'Date',
    'supervisor.clockIn': 'Clock in',
    'supervisor.clockOut': 'Clock out',
    'supervisor.openStatus': 'Open',
    'supervisor.interval': 'Break',
    'supervisor.total': 'Total',
    'jobStatus.planned': 'Planned',
    'jobStatus.active': 'Active',
    'jobStatus.paused': 'Paused',
    'jobStatus.completed': 'Completed',
    'jobStatus.cancelled': 'Cancelled',
    'assignment.scheduled': 'Scheduled',
    'assignment.working': 'Working',
    'assignment.breakTime': 'On break',
    'assignment.finished': 'Finished',
    'assignment.noEntry': 'No clock-in',
    'assignment.absent': 'Absent',
    'audit.reportTitle': 'Full Localization Audit Report',
  },
  AppLanguage.pt: {
    'app.title': 'Field Time',
    'brand.byDeveloper': 'por JKDD TECH',
    'common.ok': 'OK',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.done': 'Concluído',
    'common.close': 'Fechar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.pending': 'Pendente',
    'common.open': 'Aberta',
    'common.unavailable': 'Indisponível',
    'common.none': 'Nenhum',
    'common.localExcel': 'Excel local',
    'common.comingSoon': 'Em breve',
    'common.systemDefault': 'Padrão do sistema',
    'common.landscape': 'Paisagem',
    'common.portrait': 'Retrato',
    'common.letter': 'Carta',
    'common.us': 'EUA',
    'common.recordsCount': '{count} registros',
    'common.receiptsTotal': '{count} recibos - {total} no total',
    'common.peopleCount': '{count} pessoas',
    'common.peopleScheduled': '{count} pessoas programadas',
    'common.peopleWorking': '{count} trabalhando',
    'common.noEntryCount': '{count} sem entrada',
    'common.all': 'Todos',
    'common.details': 'Detalhes',
    'common.discard': 'Descartar',
    'common.saveChanges': 'Salvar alterações',
    'common.registrationNumber': 'Número de Cadastro',
    'common.generatedAutomatically': 'Gerado automaticamente',
    'auth.testEnvironment': 'AMBIENTE DE TESTE',
    'auth.username': 'E-mail ou usuário',
    'auth.password': 'Senha',
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'auth.logoutHelp': 'Encerrar a sessão local de teste atual',
    'auth.logoutConfirm': 'Deseja sair e voltar para a tela de login?',
    'auth.invalidCredentials': 'Usuário ou senha inválidos.',
    'auth.showPassword': 'Mostrar senha',
    'auth.hidePassword': 'Ocultar senha',
    'auth.roleCollaborator': 'Colaborador',
    'auth.roleSupervisor': 'Supervisor',
    'auth.roleDirector': 'Diretor',
    'maps.openNavigation': 'Abrir navegação',
    'maps.navigate': 'Navegar',
    'maps.routeToJob': 'Rota para a obra',
    'maps.chooseApp': 'Escolha o aplicativo de mapa',
    'maps.openWaze': 'Abrir no Waze',
    'maps.openGoogleMaps': 'Abrir no Google Maps',
    'maps.openAppleMaps': 'Abrir no Apple Maps',
    'jobs.payPremium': 'Adicional Salarial',
    'jobs.noPayPremium': 'Sem adicional salarial',
    'jobs.travelBonusValue': 'Travel Bonus {hours}',
    'jobs.payPremiumValue': 'Adicional {value}',
    'timesheet.generateTimesheet': 'Gerar Timesheet',
    'timesheet.payPremium': 'Adicional Salarial',
    'employees.setInactive': 'Desativar',
    'employees.setActive': 'Reativar',
    'employees.confirmInactive': 'Deseja desativar este colaborador?',
    'employees.confirmActive': 'Deseja reativar este colaborador?',
    'employees.statusSaved': 'Status do colaborador salvo.',
    'profiles.saveCurrent':
        'Deseja salvar este perfil como perfil de teste atual?',
    'supervisor.president': 'Diretor',
    'supervisor.director': 'Diretor',
    'supervisor.hoursApprovedSuccess': 'Horas aprovadas com sucesso.',
    'supervisor.hoursRejectedSuccess': 'Horas rejeitadas com sucesso.',
    'supervisor.correctionRequestedSuccess': 'Correção solicitada com sucesso.',
    'supervisor.cannotReviewOwnTime':
        'Você não pode aprovar nem rejeitar os próprios registros de horas.',
    'supervisor.travelBonusUpdatedSuccess':
        'Bônus de viagem atualizado com sucesso.',
    'timesheet.generatedSuccess': 'Timesheet gerado com sucesso.',
    'timesheet.generationError': 'Não foi possível gerar o timesheet.',
    'timesheet.noRecordsForPeriod':
        'Nenhum registro de horas foi encontrado neste período.',
    'fieldTime.localDataLoaded': 'Dados locais carregados.',
    'fieldTime.clockInProgress': 'Registrando entrada...',
    'fieldTime.clockInSuccess': 'Entrada registrada em {job}.',
    'fieldTime.switchJobProgress': 'Trocando obra...',
    'fieldTime.switchJobSuccess': 'Novo período iniciado em {job}.',
    'fieldTime.endDayProgress': 'Encerrando o dia...',
    'fieldTime.endDaySuccess': 'Expediente encerrado com sucesso.',
    'fieldTime.savePhotoProgress': 'Salvando foto...',
    'fieldTime.photoLinked': 'Foto vinculada à obra {job}.',
    'fieldTime.saveReceiptProgress': 'Salvando recibo...',
    'fieldTime.reimbursementSubmitted': 'Reembolso enviado para aprovação.',
    'fieldTime.draftSaved': 'Rascunho salvo.',
    'fieldTime.saveObservationProgress': 'Salvando observação...',
    'fieldTime.observationAdded': 'Observação adicionada ao período atual.',
    'fieldTime.operationFailed': 'Não foi possível concluir a operação.',
    'fieldTime.deviceSaveFailed':
        'Não foi possível salvar os dados neste dispositivo.',
    'fieldTime.openPeriodExists': 'Já existe um período aberto.',
    'fieldTime.clockInBeforeSwitchJob':
        'Registre entrada antes de trocar de obra.',
    'fieldTime.selectDifferentJob': 'Selecione uma obra diferente da atual.',
    'fieldTime.invalidSwitchTime': 'Horário de troca inválido.',
    'fieldTime.noOpenWorkday': 'Não existe expediente aberto.',
    'fieldTime.invalidClockOutTime': 'Horário de saída inválido.',
    'fieldTime.confirmReceiptBeforeSubmit':
        'Revise e confirme os dados antes de enviar.',
    'fieldTime.invalidReceiptFields':
        'Preencha estabelecimento, descrição e valor corretamente.',
    'fieldTime.duplicateRegistration':
        'UUID ou número de cadastro duplicado. O registro não foi salvo.',
    'fieldTime.clockInBeforeObservation':
        'Registre entrada antes de adicionar observações.',
    'fieldTime.typeObservation': 'Digite uma observação.',
    'nav.home': 'Início',
    'nav.timesheet': 'Timesheet',
    'nav.jobs': 'Obras',
    'nav.receipts': 'Recibos',
    'nav.employees': 'Colaboradores',
    'nav.management': 'Gestão',
    'nav.menu': 'Menu',
    'home.dailySummary': 'Resumo do dia',
    'home.hoursWorked': 'Horas trabalhadas',
    'home.bonusHours': 'Horas de bônus',
    'home.jobsVisited': 'Obras visitadas',
    'home.receipts': 'Recibos',
    'home.reimbursements': 'Reembolsos',
    'home.pendingSync': 'Sincronização pendente',
    'home.goodMorning': 'Bom dia',
    'home.goodAfternoon': 'Boa tarde',
    'home.goodEvening': 'Boa noite',
    'home.workdayInProgress': 'Expediente em andamento',
    'home.readyToClockIn': 'Pronto para registrar entrada',
    'home.clockedIn': 'Entrada registrada',
    'home.clockedOut': 'Fora do expediente',
    'home.online': 'Online',
    'home.offline': 'Offline',
    'home.pendingItems': '{count} pendentes',
    'home.currentStatus': 'Status atual',
    'home.currentStatusSubtitle': 'Visão geral da atividade em campo.',
    'home.noActiveJob': 'Nenhuma obra ativa',
    'home.selectJobWhenClockingIn': 'Selecione uma obra ao registrar entrada.',
    'home.clockInTime': 'Horário de entrada',
    'home.workedTime': 'Tempo trabalhado',
    'home.gps': 'GPS',
    'home.clientCompany': 'Empresa contratante',
    'home.subcontractor': 'Colaborador',
    'home.currentNote': 'Observação atual',
    'home.primaryAction': 'Ação principal',
    'home.secondaryActions': 'Ações secundárias',
    'home.clockIn': 'REGISTRAR ENTRADA',
    'home.endWorkday': 'ENCERRAR DIA',
    'home.switchJob': 'Trocar obra',
    'home.attachReceipt': 'Anexar recibo',
    'home.requestReimbursement': 'Pedir reembolso',
    'home.addPhoto': 'Adicionar foto',
    'home.addNote': 'Adicionar observação',
    'home.myTimesheet': 'Meu timesheet',
    'home.todayTimesheet': 'Timesheet de hoje',
    'home.todayTimeline':
        'Linha do tempo dos períodos trabalhados neste dispositivo.',
    'home.noWorkPeriods': 'Nenhum período trabalhado ainda',
    'home.noWorkPeriodsHelp':
        'Registre a entrada para iniciar o timesheet de hoje.',
    'home.receiptsAndReimbursements': 'Recibos e reembolsos',
    'home.noReceiptsYet': 'Nenhum recibo ainda',
    'home.noReceiptsYetHelp':
        'Anexe um recibo quando uma despesa da obra precisar de reembolso.',
    'home.excellentWorkday': 'Tenha um excelente dia de trabalho',
    'home.workSafely': 'Trabalhe com segurança',
    'home.goodRest': 'Tenha um bom descanso',
    'endDay.title': 'Encerrar dia de trabalho?',
    'endDay.message':
        'Tem certeza que deseja encerrar o dia de trabalho? O período atual será fechado com o horário atual e o status do GPS.',
    'endDay.confirm': 'Sim, encerrar dia',
    'endDay.success': 'Expediente encerrado com sucesso',
    'endDay.rest': 'Tenha um bom descanso',
    'endDay.tomorrow': 'Nos vemos amanhã',
    'endDay.summary': 'Resumo do dia',
    'endDay.firstClockIn': 'Primeira entrada',
    'endDay.lastClockOut': 'Última saída',
    'endDay.receiptsSubmitted': 'Recibos enviados',
    'endDay.weekHours': 'Horas da semana',
    'endDay.receiptQuestion':
        'Você tem recibos ou documentos para anexar antes de encerrar o expediente?',
    'endDay.attachNow': 'Anexar agora',
    'endDay.noReceipts': 'Sem recibos',
    'endDay.viewTimesheet': 'Ver meu timesheet',
    'photo.clockInRequired':
        'Registre entrada antes de adicionar foto da obra.',
    'photo.addPhoto': 'Adicionar foto',
    'photo.takePhoto': 'Tirar foto',
    'photo.selectImage': 'Selecionar imagem',
    'photo.cameraUnavailable':
        'A câmera ou galeria não pôde ser aberta neste dispositivo.',
    'note.clockInRequired': 'Registre entrada antes de adicionar observações.',
    'note.currentPeriod': 'Observação do período atual',
    'note.hint': 'Digite uma observação',
    'jobs.title': 'Obras',
    'jobs.subtitle': 'Diretório visual das obras disponíveis no Field Time.',
    'jobs.search': 'Pesquisar',
    'jobs.active': 'Ativa',
    'jobs.inactive': 'Inativa',
    'jobs.address': 'Endereço',
    'jobs.city': 'Cidade',
    'jobs.state': 'Estado',
    'jobs.zipCode': 'ZIP Code',
    'jobs.status': 'Status',
    'jobs.noJobsFound': 'Nenhuma obra encontrada',
    'jobs.noJobsAvailable': 'Nenhuma obra disponível',
    'jobs.noJobsAvailableHelp':
        'Importe obras em data_import/input antes de registrar entrada.',
    'jobs.selectJob': 'Selecionar obra',
    'jobs.selectJobForClockIn': 'Selecionar obra para registrar entrada',
    'jobs.switchToWhichJob': 'Trocar para qual obra?',
    'jobs.currentJob': 'Obra atual',
    'jobs.openJob': 'Abrir obra',
    'jobs.viewJob': 'Ver obra',
    'jobs.newJob': 'Nova obra',
    'jobs.jobNumber': 'Número da obra',
    'jobs.jobName': 'Nome da obra',
    'jobs.allowSupervisorCreateJobs':
        'Permitir que o Supervisor cadastre obras',
    'jobs.fixedTeamsDisabled': 'Sem equipes fixas: alocação por data e obra.',
    'jobs.listTitle': 'Lista de obras',
    'jobs.all': 'Todas as obras',
    'jobs.withBonus': 'Com bônus',
    'jobs.details': 'Detalhes da obra',
    'jobs.client': 'Cliente',
    'jobs.supervisor': 'Supervisor',
    'jobs.travelBonus': 'Travel Bonus',
    'jobs.accessInstructions': 'Instruções de acesso',
    'jobs.location': 'Localização',
    'jobs.selectThisJob': 'Selecionar obra',
    'jobs.openMap': 'Abrir mapa',
    'jobs.newJobRequest': 'Solicitar nova obra',
    'jobs.newJobAdmin': '+ CADASTRAR NOVA OBRA',
    'jobs.pendingRequest': 'Solicitação pendente',
    'jobs.duplicateWarning': 'Possível duplicidade de número ou endereço.',
    'jobs.requestPrepared':
        'Solicitação de nova obra preparada para revisão do supervisor.',
    'employees.management': 'Gestão de Colaboradores',
    'employees.subtitle':
        'Diretório de colaboradores importados para as operações do Field Time.',
    'employees.add': '+ Cadastrar Colaborador',
    'employees.edit': 'Editar colaborador',
    'employees.deactivate': 'Desativar colaborador',
    'employees.delete': 'Excluir colaborador',
    'employees.deleteBlocked':
        'Colaboradores com histórico não podem ser excluídos.',
    'employees.details': 'Detalhes do colaborador',
    'employees.search': 'Pesquisar por nome ou Employee ID',
    'employees.status': 'Status',
    'employees.activeStatus': 'Ativo',
    'employees.inactiveStatus': 'Inativo',
    'employees.company': 'Empresa',
    'employees.category': 'Categoria',
    'employees.supervisor': 'Supervisor',
    'employees.role': 'Função',
    'employees.all': 'Todos',
    'employees.noneFound': 'Nenhum colaborador encontrado',
    'employees.noneFoundHelp':
        'Ajuste a pesquisa ou os filtros para encontrar colaboradores.',
    'employees.unavailable': 'Banco de colaboradores indisponível',
    'employees.loadError':
        'O arquivo de colaboradores está ausente ou inválido. Confira assets/data/employees.json.',
    'employees.employeeId': 'Employee ID',
    'employees.name': 'Nome',
    'employees.phone': 'Telefone',
    'employees.email': 'E-mail',
    'employees.address': 'Endereço',
    'employees.emergencyContact': 'Contato de emergência',
    'employees.notes': 'Observações',
    'employees.required': 'Campo obrigatório',
    'timesheet.title': 'Timesheet',
    'timesheet.subtitle':
        'Revise horas, obras, recibos e prontidão para exportação.',
    'timesheet.generatePdf': 'Gerar PDF',
    'timesheet.previewPdf': 'Visualizar PDF',
    'timesheet.share': 'Compartilhar',
    'timesheet.download': 'Baixar',
    'timesheet.period': 'Período',
    'timesheet.today': 'Hoje',
    'timesheet.week': 'Semana',
    'timesheet.month': 'Mês',
    'timesheet.year': 'Ano',
    'timesheet.dailyRecords': 'Registros diários',
    'timesheet.noRecords': 'Nenhuma informação encontrada',
    'timesheet.noRecordsHelp': 'Períodos trabalhados aparecerão aqui.',
    'timesheet.regularHours': 'Horas regulares',
    'timesheet.bonusHours': 'Horas de bônus',
    'timesheet.totalHours': 'Total de horas',
    'timesheet.totalByJob': 'Total por obra',
    'timesheet.jobs': 'Obras',
    'timesheet.receipts': 'Recibos',
    'timesheet.reimbursements': 'Reembolsos',
    'timesheet.date': 'Data',
    'timesheet.job': 'Obra',
    'timesheet.name': 'Nome',
    'timesheet.address': 'Endereço',
    'timesheet.clockIn': 'Entrada',
    'timesheet.clockOut': 'Saída',
    'timesheet.duration': 'Duração',
    'timesheet.hours': 'Horas',
    'timesheet.bonus': 'Bônus',
    'timesheet.total': 'Total',
    'timesheet.approval': 'Aprovação',
    'timesheet.notes': 'Observações',
    'timesheet.inProgress': 'Em andamento',
    'timesheet.fileName': 'field_time_timesheet.pdf',
    'timesheet.travelBonusLine': 'Travel Bonus',
    'timesheet.totalWorkedHours': 'Total de horas trabalhadas',
    'timesheet.totalTravelBonus': 'Total de Travel Bonus',
    'timesheet.grandTotal': 'Total geral',
    'pdf.title': 'Timesheet do Field Time',
    'pdf.totalGeneral': 'Total geral: {total}',
    'pdf.totalWorkedHours': 'Total de horas trabalhadas: {total}',
    'pdf.totalTravelBonus': 'Total de Travel Bonus: {total}',
    'pdf.receiptsSummary': 'Resumo dos recibos',
    'pdf.noLinkedReceipts': 'Nenhum recibo vinculado a obra nesta semana.',
    'pdf.worker': 'Colaborador: {worker}',
    'pdf.contractor': 'Contratante: {contractor}',
    'pdf.subcontractor': 'Empresa prestadora: {subcontractor}',
    'pdf.responsible': 'Responsável: {worker}',
    'pdf.period': 'Período: {start} até {end}',
    'pdf.week': 'Semana: segunda-feira a domingo',
    'pdf.noRecords': 'Sem registros',
    'pdf.receipt': 'Recibo - {merchant}',
    'receipts.title': 'Recibos',
    'receipts.andReimbursements': 'Recibos e reembolsos',
    'receipts.addReceipt': 'Adicionar recibo',
    'receipts.attachReceipt': 'Anexar recibo',
    'receipts.camera': 'Câmera',
    'receipts.gallery': 'Galeria',
    'receipts.takePhoto': 'Tirar foto',
    'receipts.selectImage': 'Selecionar imagem',
    'receipts.merchant': 'Estabelecimento',
    'receipts.date': 'Data',
    'receipts.amount': 'Valor',
    'receipts.tax': 'Imposto',
    'receipts.receiptNumber': 'Número do recibo',
    'receipts.description': 'Descrição',
    'receipts.category': 'Categoria',
    'receipts.observation': 'Observação',
    'receipts.notes': 'Observações',
    'receipts.submit': 'Enviar',
    'receipts.send': 'Enviar',
    'receipts.saveDraft': 'Salvar rascunho',
    'receipts.file': 'Arquivo: {name}',
    'receipts.reviewConfirm': 'Revisei e confirmo as informações',
    'receipts.mockNotice':
        'A leitura automática de recibos está preparada, mas ainda usa modo simulado. Nenhum dado será inventado: revise, corrija e confirme antes de enviar.',
    'receipts.automaticReadingNotIntegrated':
        'A leitura automática de recibos ainda não está integrada. Revise e preencha os campos.',
    'receipts.noReceiptsDevice': 'Nenhum recibo neste dispositivo',
    'receipts.noReceiptsDeviceHelp':
        'Use Anexar recibo para capturar uma despesa e pedir reembolso.',
    'receipts.cameraUnavailable': 'A câmera ou galeria não pôde ser aberta.',
    'receipts.attachPhotoRequired': 'Anexe uma foto ou imagem do recibo.',
    'receipts.requiredField': 'Campo obrigatório',
    'receipts.invalidAmount': 'Valor inválido',
    'receiptStatus.draft': 'Rascunho',
    'receiptStatus.submitted': 'Enviado',
    'receiptStatus.underReview': 'Em análise',
    'receiptStatus.approved': 'Aprovado',
    'receiptStatus.rejected': 'Rejeitado',
    'receiptStatus.paid': 'Pago',
    'settings.title': 'Configurações',
    'settings.subtitle': 'Perfil, controles do piloto e preferências do app.',
    'settings.preferences': 'Preferências',
    'settings.language': 'Idioma',
    'settings.languageHelp': 'Escolha o idioma do aplicativo.',
    'settings.saved': 'Idioma salvo.',
    'settings.unsavedChanges': 'Alterações não salvas',
    'settings.unsavedDialogTitle': 'Configurações alteradas',
    'settings.unsavedDialogMessage':
        'Você possui alterações de configuração não salvas. O que deseja fazer antes de sair?',
    'settings.discarded': 'Alterações descartadas.',
    'settings.draftRecovered':
        'Há um rascunho de configurações disponível para revisão.',
    'settings.data': 'Dados',
    'settings.account': 'Conta',
    'settings.profile': 'Perfil',
    'settings.company': 'Empresa',
    'settings.permissions': 'Permissões',
    'settings.theme': 'Tema',
    'settings.dateFormat': 'Formato de data',
    'settings.dateFormatValue': 'MM/DD/AAAA',
    'settings.timeFormat': 'Formato de hora',
    'settings.timeFormatValue': '12 horas',
    'settings.units': 'Unidades',
    'settings.reports': 'Relatórios',
    'settings.timesheetFormat': 'Formato do timesheet',
    'settings.paperSize': 'Tamanho do papel',
    'settings.defaultPaperSize': 'Tamanho padrão do papel',
    'settings.orientation': 'Orientação',
    'settings.pdfOrientation': 'Orientação do PDF',
    'settings.about': 'Sobre',
    'settings.version': 'Versão',
    'settings.privacy': 'Privacidade',
    'settings.terms': 'Termos',
    'settings.restoreDefault': 'Restaurar padrão',
    'settings.landscapePlanned': 'Paisagem planejada',
    'import.title': 'Importação de Obras',
    'import.subtitle':
        'Banco local de obras para o Field Time. Funciona offline.',
    'import.updateJobs': 'Atualizar obras',
    'import.viewReport': 'Ver relatório',
    'import.lastUpdate': 'Última atualização',
    'import.lastFile': 'Último arquivo processado',
    'import.jobsCount': 'Quantidade de obras',
    'import.errorCount': 'Quantidade de erros',
    'import.processedFile': 'Arquivo processado',
    'import.noSpreadsheet': 'Nenhuma planilha encontrada',
    'import.noFileProcessed': 'Nenhum arquivo processado',
    'import.pending': 'Pendente',
    'import.summary': 'Resumo',
    'import.databaseUnavailable': 'Banco de obras indisponível',
    'import.loadError':
        'O arquivo de obras está ausente ou inválido. Importe a planilha novamente e confira o JOBS_IMPORT_REPORT.md.',
    'import.reviewReport': 'Revise o relatório antes de usar a base no campo.',
    'import.updateInstructions':
        'Substitua a planilha atualizada em data_import/input/ e execute dart run tool/import_jobs_from_excel.dart. Upload remoto não foi implementado nesta etapa.',
    'import.reportTitle': 'Relatório de Importação',
    'import.reportInstructions':
        'O relatório local é gerado em data_import/reports/JOBS_IMPORT_REPORT.md.',
    'approval.approve': 'Aprovar',
    'approval.reject': 'Rejeitar',
    'approval.review': 'Revisar',
    'approval.pending': 'Pendente',
    'approval.approved': 'Aprovado',
    'approval.rejected': 'Rejeitado',
    'approval.underReview': 'Em revisão',
    'approval.corrected': 'Corrigido',
    'approval.resubmitted': 'Reenviado',
    'approval.correctionRequested': 'Correção solicitada',
    'approval.closed': 'Fechado',
    'approval.working': 'Trabalhando',
    'approval.reason': 'Motivo',
    'approval.observation': 'Observação',
    'approval.confirmation': 'Confirmação',
    'approval.history': 'Histórico',
    'approval.approvedBy': 'Aprovado por',
    'approval.rejectedBy': 'Rejeitado por',
    'approval.reviewedBy': 'Revisado por',
    'approval.confirmApprove': 'Aprovar este registro?',
    'approval.confirmReject': 'Rejeitar este registro?',
    'approval.approveMessage':
        'O registro será marcado como Aprovado, bloqueado para edições comuns e liberado para Timesheet e relatórios.',
    'approval.rejectMessage':
        'O registro será devolvido ao colaborador com o motivo informado.',
    'approval.confirmApproveTitle': 'Confirmar aprovação',
    'approval.approvalObservation': 'Observação da aprovação',
    'approval.rejectRecord': 'Rejeitar registro',
    'approval.rejectionReasonRequired': 'Motivo obrigatório da rejeição',
    'approval.reviewRecord': 'Revisar registro',
    'approval.reviewRequest': 'Correção ou conferência solicitada',
    'approval.additionalObservations': 'Observações adicionais',
    'approval.sendToReview': 'Enviar para revisão',
    'approval.reviewEntry': 'Revisar registro',
    'approval.clockIn': 'Entrada',
    'approval.clockOut': 'Saída',
    'approval.breakMinutes': 'Intervalo min',
    'approval.travelBonus': 'Travel Bonus',
    'approval.requiredJustification': 'Justificativa obrigatória',
    'approval.saveReview': 'Salvar revisão',
    'approval.approveAll': 'Aprovar todos',
    'approval.approveAllValid': 'Aprovar todos válidos',
    'approval.noSubmittedRecords': 'Sem registros enviados',
    'approval.noSubmittedRecordsHelp':
        'Registros pendentes de Employee e Contractor aparecem aqui.',
    'supervisor.title': 'Central do Supervisor',
    'supervisor.management': 'Gestão',
    'supervisor.approveTime': 'Aprovar Horas',
    'supervisor.schedule': 'Programação',
    'supervisor.jobs': 'Obras',
    'supervisor.peopleByJob': 'Equipe por Obra',
    'supervisor.workingNow': 'Trabalhando Agora',
    'supervisor.pilotMode': 'modo piloto',
    'supervisor.managementUnavailable': 'Gestão indisponível',
    'supervisor.clockInSimulated': 'Entrada simulada no piloto.',
    'supervisor.breakStarted': 'Intervalo iniciado no piloto.',
    'supervisor.breakEnded': 'Intervalo finalizado no piloto.',
    'supervisor.hoursSent': 'Horas enviadas.',
    'supervisor.roleChanged': 'Modo de teste alterado.',
    'supervisor.createJobsAllowed':
        'Supervisor pode cadastrar obras no piloto.',
    'supervisor.createJobsBlocked':
        'Cadastro de obras por Supervisor bloqueado.',
    'supervisor.jobCreated': 'Nova obra criada no piloto.',
    'supervisor.jobUpdated': 'Obra atualizada.',
    'supervisor.employeeOrContractorOnly':
        'Apenas perfis Employee ou Contractor registram horas.',
    'supervisor.hoursCorrectedResubmitted':
        'Horas corrigidas e reenviadas para aprovação.',
    'supervisor.hoursSentForApproval': 'Horas enviadas para aprovação.',
    'supervisor.correctionReasonRequired': 'Informe o motivo da solicitação.',
    'supervisor.correctionSent': 'Correção enviada para nova revisão.',
    'supervisor.entryApproved': 'Registro aprovado.',
    'supervisor.entryRejected': 'Registro rejeitado.',
    'supervisor.entrySentToReview': 'Registro enviado para revisão.',
    'supervisor.approvedRecordLocked':
        'Registro aprovado está bloqueado para edições comuns.',
    'supervisor.changeJustificationRequired':
        'Toda alteração precisa de justificativa.',
    'supervisor.reviewSavedAudit': 'Revisão salva com registro de auditoria.',
    'supervisor.batchApproveJustificationRequired':
        'Informe uma justificativa para aprovar em lote.',
    'supervisor.validRecordsApproved': 'Registros válidos aprovados.',
    'supervisor.reviewJustificationRequired':
        'Informe a justificativa da revisão.',
    'supervisor.rejectionReasonRequired': 'Informe o motivo da rejeição.',
    'supervisor.permissionDenied':
        'Perfil sem permissão para executar esta ação.',
    'supervisor.noAssignedJob':
        'Nenhuma obra está atribuída a este colaborador.',
    'supervisor.testMode': 'Modo de teste',
    'supervisor.rbacUpdates':
        'A interface atualiza imediatamente conforme o RBAC.',
    'supervisor.pendingHours': 'Horas pendentes',
    'supervisor.approvedHours': 'Horas aprovadas',
    'supervisor.rejectedHours': 'Horas rejeitadas',
    'supervisor.activeJobs': 'Obras ativas',
    'supervisor.openClockIns': 'Entradas abertas',
    'supervisor.reviewSubmittedRecords': 'Revisar registros enviados',
    'supervisor.dailyRoute': 'Rota diária do supervisor',
    'supervisor.jobsAndDetails': 'Obras e detalhes da obra',
    'supervisor.dailyAllocation': 'Alocação diária por obra',
    'supervisor.today': 'Hoje',
    'supervisor.week': 'Semana',
    'supervisor.calendar': 'Calendário',
    'supervisor.currentWorkerJob': 'Minha obra de hoje',
    'supervisor.workerJobSubtitle':
        'Minha programação, minhas horas e correções.',
    'supervisor.noHoursSent': 'Sem horas enviadas',
    'supervisor.noHoursSentHelp': 'Registros do perfil atual aparecem aqui.',
    'supervisor.requestCorrection': 'Solicitar correção',
    'supervisor.correctionReason': 'Motivo da correção',
    'supervisor.observation': 'Observação',
    'supervisor.optionalNote': 'Nota opcional',
    'supervisor.employee': 'Funcionário',
    'supervisor.contractor': 'Contratado',
    'supervisor.owner': 'Proprietário',
    'supervisor.administrator': 'Administrador',
    'supervisor.coordinator': 'Coordenador',
    'supervisor.employeeNote': 'Observação do funcionário',
    'supervisor.supervisorNote': 'Observação do supervisor',
    'supervisor.rejectionReason': 'Motivo da rejeição',
    'supervisor.reviewRequest': 'Solicitação de revisão',
    'supervisor.openRoute': 'Abrir rota',
    'supervisor.client': 'Cliente',
    'supervisor.supervisor': 'Supervisor',
    'supervisor.scheduledToday': 'Programadas hoje',
    'supervisor.hoursToday': 'Horas hoje',
    'supervisor.peopleScheduled': 'Pessoas programadas',
    'supervisor.peopleWorking': 'Pessoas trabalhando',
    'supervisor.withoutClockIn': 'Sem entrada',
    'supervisor.totalDayHours': 'Total de horas do dia',
    'supervisor.peopleScheduledToday': 'Pessoas programadas hoje',
    'supervisor.peopleWorkingNow': 'Pessoas trabalhando agora',
    'supervisor.noChanges': 'Sem alterações',
    'supervisor.noChangesHelp': 'Alterações e aprovações aparecem aqui.',
    'supervisor.jobInfo': 'Informações',
    'supervisor.summary': 'Resumo',
    'supervisor.peopleToday': 'Pessoas de Hoje',
    'supervisor.hours': 'Horas',
    'supervisor.history': 'Histórico',
    'supervisor.number': 'Número',
    'supervisor.startDate': 'Data de início',
    'supervisor.scheduledTime': 'Horário previsto',
    'supervisor.editByPermission': 'Editar conforme permissão',
    'supervisor.visualEditEnabled': 'Edição visual habilitada no piloto.',
    'supervisor.nobodyWorking': 'Ninguém trabalhando agora',
    'supervisor.openEntriesAppear': 'Entradas abertas aparecem aqui.',
    'supervisor.viewRecord': 'Ver registro',
    'supervisor.viewJob': 'Ver obra',
    'supervisor.person': 'Pessoa',
    'supervisor.role': 'Função',
    'supervisor.assignedBy': 'Atribuído por',
    'supervisor.period': 'Período',
    'supervisor.status': 'Status',
    'supervisor.notes': 'Observações',
    'supervisor.job': 'Obra',
    'supervisor.date': 'Data',
    'supervisor.clockIn': 'Entrada',
    'supervisor.clockOut': 'Saída',
    'supervisor.openStatus': 'Aberta',
    'supervisor.interval': 'Intervalo',
    'supervisor.total': 'Total',
    'jobStatus.planned': 'Planejada',
    'jobStatus.active': 'Ativa',
    'jobStatus.paused': 'Pausada',
    'jobStatus.completed': 'Concluída',
    'jobStatus.cancelled': 'Cancelada',
    'assignment.scheduled': 'Programado',
    'assignment.working': 'Trabalhando',
    'assignment.breakTime': 'Em intervalo',
    'assignment.finished': 'Finalizado',
    'assignment.noEntry': 'Sem entrada',
    'assignment.absent': 'Ausente',
    'audit.reportTitle': 'Relatório Completo de Auditoria de Idioma',
  },
  AppLanguage.es: {
    'app.title': 'Field Time',
    'brand.byDeveloper': 'por JKDD TECH',
    'common.ok': 'OK',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.done': 'Listo',
    'common.close': 'Cerrar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.pending': 'Pendiente',
    'common.open': 'Abierta',
    'common.unavailable': 'No disponible',
    'common.none': 'Ninguno',
    'common.localExcel': 'Excel local',
    'common.comingSoon': 'Próximamente',
    'common.systemDefault': 'Predeterminado del sistema',
    'common.landscape': 'Horizontal',
    'common.portrait': 'Vertical',
    'common.letter': 'Carta',
    'common.us': 'EE. UU.',
    'common.recordsCount': '{count} registros',
    'common.receiptsTotal': '{count} recibos - {total} en total',
    'common.peopleCount': '{count} personas',
    'common.peopleScheduled': '{count} personas programadas',
    'common.peopleWorking': '{count} trabajando',
    'common.noEntryCount': '{count} sin entrada',
    'common.all': 'Todos',
    'common.details': 'Detalles',
    'common.discard': 'Descartar',
    'common.saveChanges': 'Guardar cambios',
    'common.registrationNumber': 'Número de Registro',
    'common.generatedAutomatically': 'Generado automáticamente',
    'auth.testEnvironment': 'ENTORNO DE PRUEBA',
    'auth.username': 'Correo o usuario',
    'auth.password': 'Contraseña',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Salir',
    'auth.logoutHelp': 'Cerrar la sesión local de prueba actual',
    'auth.logoutConfirm':
        '¿Desea salir y volver a la pantalla de inicio de sesión?',
    'auth.invalidCredentials': 'Usuario o contraseña inválidos.',
    'auth.showPassword': 'Mostrar contraseña',
    'auth.hidePassword': 'Ocultar contraseña',
    'auth.roleCollaborator': 'Colaborador',
    'auth.roleSupervisor': 'Supervisor',
    'auth.roleDirector': 'Director',
    'maps.openNavigation': 'Abrir navegación',
    'maps.navigate': 'Navegar',
    'maps.routeToJob': 'Ruta al trabajo',
    'maps.chooseApp': 'Elija la aplicación de mapas',
    'maps.openWaze': 'Abrir en Waze',
    'maps.openGoogleMaps': 'Abrir en Google Maps',
    'maps.openAppleMaps': 'Abrir en Apple Maps',
    'jobs.payPremium': 'Adicional Salarial',
    'jobs.noPayPremium': 'Sin adicional salarial',
    'jobs.travelBonusValue': 'Travel Bonus {hours}',
    'jobs.payPremiumValue': 'Adicional {value}',
    'timesheet.generateTimesheet': 'Generar Timesheet',
    'timesheet.payPremium': 'Adicional Salarial',
    'employees.setInactive': 'Desactivar',
    'employees.setActive': 'Reactivar',
    'employees.confirmInactive': 'Desea desactivar este colaborador?',
    'employees.confirmActive': 'Desea reactivar este colaborador?',
    'employees.statusSaved': 'Estado del colaborador guardado.',
    'profiles.saveCurrent':
        'Desea guardar este perfil como perfil de prueba actual?',
    'supervisor.president': 'Director',
    'supervisor.director': 'Director',
    'supervisor.hoursApprovedSuccess': 'Horas aprobadas correctamente.',
    'supervisor.hoursRejectedSuccess': 'Horas rechazadas correctamente.',
    'supervisor.correctionRequestedSuccess':
        'Corrección solicitada correctamente.',
    'supervisor.cannotReviewOwnTime':
        'No puede aprobar ni rechazar sus propios registros de horas.',
    'supervisor.travelBonusUpdatedSuccess':
        'Bono de viaje actualizado correctamente.',
    'timesheet.generatedSuccess': 'Timesheet generado correctamente.',
    'timesheet.generationError': 'No se pudo generar el timesheet.',
    'timesheet.noRecordsForPeriod':
        'No se encontraron registros de horas para este período.',
    'fieldTime.localDataLoaded': 'Datos locales cargados.',
    'fieldTime.clockInProgress': 'Registrando entrada...',
    'fieldTime.clockInSuccess': 'Entrada registrada en {job}.',
    'fieldTime.switchJobProgress': 'Cambiando obra...',
    'fieldTime.switchJobSuccess': 'Nuevo período iniciado en {job}.',
    'fieldTime.endDayProgress': 'Cerrando la jornada...',
    'fieldTime.endDaySuccess': 'Jornada finalizada correctamente.',
    'fieldTime.savePhotoProgress': 'Guardando foto...',
    'fieldTime.photoLinked': 'Foto vinculada a la obra {job}.',
    'fieldTime.saveReceiptProgress': 'Guardando recibo...',
    'fieldTime.reimbursementSubmitted': 'Reembolso enviado para aprobación.',
    'fieldTime.draftSaved': 'Borrador guardado.',
    'fieldTime.saveObservationProgress': 'Guardando observación...',
    'fieldTime.observationAdded': 'Observación agregada al período actual.',
    'fieldTime.operationFailed': 'No se pudo completar la operación.',
    'fieldTime.deviceSaveFailed':
        'No se pudieron guardar los datos en este dispositivo.',
    'fieldTime.openPeriodExists': 'Ya existe un período abierto.',
    'fieldTime.clockInBeforeSwitchJob':
        'Registre entrada antes de cambiar de obra.',
    'fieldTime.selectDifferentJob':
        'Seleccione una obra diferente de la actual.',
    'fieldTime.invalidSwitchTime': 'Hora de cambio inválida.',
    'fieldTime.noOpenWorkday': 'No hay una jornada abierta.',
    'fieldTime.invalidClockOutTime': 'Hora de salida inválida.',
    'fieldTime.confirmReceiptBeforeSubmit':
        'Revise y confirme los datos antes de enviar.',
    'fieldTime.invalidReceiptFields':
        'Complete establecimiento, descripción y valor correctamente.',
    'fieldTime.duplicateRegistration':
        'UUID o número de registro duplicado. El registro no fue guardado.',
    'fieldTime.clockInBeforeObservation':
        'Registre entrada antes de agregar observaciones.',
    'fieldTime.typeObservation': 'Escriba una observación.',
    'nav.home': 'Inicio',
    'nav.timesheet': 'Timesheet',
    'nav.jobs': 'Obras',
    'nav.receipts': 'Recibos',
    'nav.employees': 'Colaboradores',
    'nav.management': 'Gestión',
    'nav.menu': 'Menú',
    'home.dailySummary': 'Resumen del día',
    'home.hoursWorked': 'Horas trabajadas',
    'home.bonusHours': 'Horas de bono',
    'home.jobsVisited': 'Obras visitadas',
    'home.receipts': 'Recibos',
    'home.reimbursements': 'Reembolsos',
    'home.pendingSync': 'Sincronización pendiente',
    'home.goodMorning': 'Buenos días',
    'home.goodAfternoon': 'Buenas tardes',
    'home.goodEvening': 'Buenas noches',
    'home.workdayInProgress': 'Jornada en curso',
    'home.readyToClockIn': 'Listo para registrar entrada',
    'home.clockedIn': 'Entrada registrada',
    'home.clockedOut': 'Fuera de jornada',
    'home.online': 'En línea',
    'home.offline': 'Sin conexión',
    'home.pendingItems': '{count} pendientes',
    'home.currentStatus': 'Estado actual',
    'home.currentStatusSubtitle': 'Vista general de la actividad en campo.',
    'home.noActiveJob': 'No hay obra activa',
    'home.selectJobWhenClockingIn': 'Seleccione una obra al registrar entrada.',
    'home.clockInTime': 'Hora de entrada',
    'home.workedTime': 'Tiempo trabajado',
    'home.gps': 'GPS',
    'home.clientCompany': 'Empresa contratante',
    'home.subcontractor': 'Colaborador',
    'home.currentNote': 'Observación actual',
    'home.primaryAction': 'Acción principal',
    'home.secondaryActions': 'Acciones secundarias',
    'home.clockIn': 'REGISTRAR ENTRADA',
    'home.endWorkday': 'CERRAR DÍA',
    'home.switchJob': 'Cambiar obra',
    'home.attachReceipt': 'Adjuntar recibo',
    'home.requestReimbursement': 'Pedir reembolso',
    'home.addPhoto': 'Agregar foto',
    'home.addNote': 'Agregar observación',
    'home.myTimesheet': 'Mi timesheet',
    'home.todayTimesheet': 'Timesheet de hoy',
    'home.todayTimeline':
        'Línea de tiempo de los períodos trabajados en este dispositivo.',
    'home.noWorkPeriods': 'Aún no hay períodos trabajados',
    'home.noWorkPeriodsHelp':
        'Registre la entrada para iniciar el timesheet de hoy.',
    'home.receiptsAndReimbursements': 'Recibos y reembolsos',
    'home.noReceiptsYet': 'Aún no hay recibos',
    'home.noReceiptsYetHelp':
        'Adjunte un recibo cuando un gasto de obra necesite reembolso.',
    'home.excellentWorkday': 'Que tenga un excelente día de trabajo',
    'home.workSafely': 'Trabaje con seguridad',
    'home.goodRest': 'Que tenga un buen descanso',
    'endDay.title': '¿Cerrar día de trabajo?',
    'endDay.message':
        '¿Está seguro de que desea cerrar el día de trabajo? El período actual se cerrará con la hora actual y el estado del GPS.',
    'endDay.confirm': 'Sí, cerrar día',
    'endDay.success': 'Jornada cerrada correctamente',
    'endDay.rest': 'Que tenga un buen descanso',
    'endDay.tomorrow': 'Nos vemos mañana',
    'endDay.summary': 'Resumen del día',
    'endDay.firstClockIn': 'Primera entrada',
    'endDay.lastClockOut': 'Última salida',
    'endDay.receiptsSubmitted': 'Recibos enviados',
    'endDay.weekHours': 'Horas de la semana',
    'endDay.receiptQuestion':
        '¿Tiene recibos o documentos para adjuntar antes de cerrar la jornada?',
    'endDay.attachNow': 'Adjuntar ahora',
    'endDay.noReceipts': 'Sin recibos',
    'endDay.viewTimesheet': 'Ver mi timesheet',
    'photo.clockInRequired':
        'Registre entrada antes de agregar una foto de la obra.',
    'photo.addPhoto': 'Agregar foto',
    'photo.takePhoto': 'Tomar foto',
    'photo.selectImage': 'Seleccionar imagen',
    'photo.cameraUnavailable':
        'No se pudo abrir la cámara o galería en este dispositivo.',
    'note.clockInRequired': 'Registre entrada antes de agregar observaciones.',
    'note.currentPeriod': 'Observación del período actual',
    'note.hint': 'Escriba una observación',
    'jobs.title': 'Obras',
    'jobs.subtitle': 'Directorio visual de obras disponibles en Field Time.',
    'jobs.search': 'Buscar',
    'jobs.active': 'Activa',
    'jobs.inactive': 'Inactiva',
    'jobs.address': 'Dirección',
    'jobs.city': 'Ciudad',
    'jobs.state': 'Estado',
    'jobs.zipCode': 'Código postal',
    'jobs.status': 'Estado',
    'jobs.noJobsFound': 'No se encontró ninguna obra',
    'jobs.noJobsAvailable': 'No hay obras disponibles',
    'jobs.noJobsAvailableHelp':
        'Importe obras en data_import/input antes de registrar entrada.',
    'jobs.selectJob': 'Seleccionar obra',
    'jobs.selectJobForClockIn': 'Seleccionar obra para registrar entrada',
    'jobs.switchToWhichJob': '¿Cambiar a qué obra?',
    'jobs.currentJob': 'Obra actual',
    'jobs.openJob': 'Abrir obra',
    'jobs.viewJob': 'Ver obra',
    'jobs.newJob': 'Nueva obra',
    'jobs.jobNumber': 'Número de obra',
    'jobs.jobName': 'Nombre de obra',
    'jobs.allowSupervisorCreateJobs':
        'Permitir que el Supervisor registre obras',
    'jobs.fixedTeamsDisabled':
        'Sin equipos fijos: asignación por fecha y obra.',
    'jobs.listTitle': 'Lista de obras',
    'jobs.all': 'Todas las obras',
    'jobs.withBonus': 'Con bono',
    'jobs.details': 'Detalles de la obra',
    'jobs.client': 'Cliente',
    'jobs.supervisor': 'Supervisor',
    'jobs.travelBonus': 'Travel Bonus',
    'jobs.accessInstructions': 'Instrucciones de acceso',
    'jobs.location': 'Ubicación',
    'jobs.selectThisJob': 'Seleccionar obra',
    'jobs.openMap': 'Abrir mapa',
    'jobs.newJobRequest': 'Solicitar nueva obra',
    'jobs.newJobAdmin': '+ REGISTRAR NUEVA OBRA',
    'jobs.pendingRequest': 'Solicitud pendiente',
    'jobs.duplicateWarning': 'Posible duplicidad de número o dirección.',
    'jobs.requestPrepared':
        'Solicitud de nueva obra preparada para revisión del supervisor.',
    'employees.management': 'Gestión de Colaboradores',
    'employees.subtitle':
        'Directorio de colaboradores importados para las operaciones de Field Time.',
    'employees.add': '+ Registrar Colaborador',
    'employees.edit': 'Editar colaborador',
    'employees.deactivate': 'Desactivar colaborador',
    'employees.delete': 'Eliminar colaborador',
    'employees.deleteBlocked':
        'Los colaboradores con historial no se pueden eliminar.',
    'employees.details': 'Detalles del colaborador',
    'employees.search': 'Buscar por nombre o Employee ID',
    'employees.status': 'Estado',
    'employees.activeStatus': 'Activo',
    'employees.inactiveStatus': 'Inactivo',
    'employees.company': 'Empresa',
    'employees.category': 'Categoría',
    'employees.supervisor': 'Supervisor',
    'employees.role': 'Función',
    'employees.all': 'Todos',
    'employees.noneFound': 'No se encontró ningún colaborador',
    'employees.noneFoundHelp':
        'Ajuste la búsqueda o los filtros para encontrar colaboradores.',
    'employees.unavailable': 'Base de colaboradores no disponible',
    'employees.loadError':
        'El archivo de colaboradores falta o no es válido. Revise assets/data/employees.json.',
    'employees.employeeId': 'Employee ID',
    'employees.name': 'Nombre',
    'employees.phone': 'Teléfono',
    'employees.email': 'Correo electrónico',
    'employees.address': 'Dirección',
    'employees.emergencyContact': 'Contacto de emergencia',
    'employees.notes': 'Observaciones',
    'employees.required': 'Campo obligatorio',
    'timesheet.title': 'Timesheet',
    'timesheet.subtitle':
        'Revise horas, obras, recibos y preparación para exportar.',
    'timesheet.generatePdf': 'Generar PDF',
    'timesheet.previewPdf': 'Vista previa PDF',
    'timesheet.share': 'Compartir',
    'timesheet.download': 'Descargar',
    'timesheet.period': 'Período',
    'timesheet.today': 'Hoy',
    'timesheet.week': 'Semana',
    'timesheet.month': 'Mes',
    'timesheet.year': 'Año',
    'timesheet.dailyRecords': 'Registros diarios',
    'timesheet.noRecords': 'No se encontró información',
    'timesheet.noRecordsHelp': 'Los períodos trabajados aparecerán aquí.',
    'timesheet.regularHours': 'Horas regulares',
    'timesheet.bonusHours': 'Horas de bono',
    'timesheet.totalHours': 'Total de horas',
    'timesheet.totalByJob': 'Total por obra',
    'timesheet.jobs': 'Obras',
    'timesheet.receipts': 'Recibos',
    'timesheet.reimbursements': 'Reembolsos',
    'timesheet.date': 'Fecha',
    'timesheet.job': 'Obra',
    'timesheet.name': 'Nombre',
    'timesheet.address': 'Dirección',
    'timesheet.clockIn': 'Entrada',
    'timesheet.clockOut': 'Salida',
    'timesheet.duration': 'Duración',
    'timesheet.hours': 'Horas',
    'timesheet.bonus': 'Bono',
    'timesheet.total': 'Total',
    'timesheet.approval': 'Aprobación',
    'timesheet.notes': 'Observaciones',
    'timesheet.inProgress': 'En curso',
    'timesheet.fileName': 'field_time_timesheet.pdf',
    'timesheet.travelBonusLine': 'Travel Bonus',
    'timesheet.totalWorkedHours': 'Total de horas trabajadas',
    'timesheet.totalTravelBonus': 'Total de Travel Bonus',
    'timesheet.grandTotal': 'Total general',
    'pdf.title': 'Timesheet de Field Time',
    'pdf.totalGeneral': 'Total general: {total}',
    'pdf.totalWorkedHours': 'Total de horas trabajadas: {total}',
    'pdf.totalTravelBonus': 'Total de Travel Bonus: {total}',
    'pdf.receiptsSummary': 'Resumen de recibos',
    'pdf.noLinkedReceipts': 'No hay recibos vinculados a una obra esta semana.',
    'pdf.worker': 'Colaborador: {worker}',
    'pdf.contractor': 'Contratante: {contractor}',
    'pdf.subcontractor': 'Empresa subcontratada: {subcontractor}',
    'pdf.responsible': 'Responsable: {worker}',
    'pdf.period': 'Período: {start} a {end}',
    'pdf.week': 'Semana: lunes a domingo',
    'pdf.noRecords': 'Sin registros',
    'pdf.receipt': 'Recibo - {merchant}',
    'receipts.title': 'Recibos',
    'receipts.andReimbursements': 'Recibos y reembolsos',
    'receipts.addReceipt': 'Agregar recibo',
    'receipts.attachReceipt': 'Adjuntar recibo',
    'receipts.camera': 'Cámara',
    'receipts.gallery': 'Galería',
    'receipts.takePhoto': 'Tomar foto',
    'receipts.selectImage': 'Seleccionar imagen',
    'receipts.merchant': 'Establecimiento',
    'receipts.date': 'Fecha',
    'receipts.amount': 'Valor',
    'receipts.tax': 'Impuesto',
    'receipts.receiptNumber': 'Número de recibo',
    'receipts.description': 'Descripción',
    'receipts.category': 'Categoría',
    'receipts.observation': 'Observación',
    'receipts.notes': 'Observaciones',
    'receipts.submit': 'Enviar',
    'receipts.send': 'Enviar',
    'receipts.saveDraft': 'Guardar borrador',
    'receipts.file': 'Archivo: {name}',
    'receipts.reviewConfirm': 'Revisé y confirmo la información',
    'receipts.mockNotice':
        'La lectura automática de recibos está preparada, pero aún usa modo simulado. No se inventará ningún dato: revise, corrija y confirme antes de enviar.',
    'receipts.automaticReadingNotIntegrated':
        'La lectura automática de recibos aún no está integrada. Revise y complete los campos.',
    'receipts.noReceiptsDevice': 'No hay recibos en este dispositivo',
    'receipts.noReceiptsDeviceHelp':
        'Use Adjuntar recibo para capturar un gasto y pedir reembolso.',
    'receipts.cameraUnavailable': 'No se pudo abrir la cámara o galería.',
    'receipts.attachPhotoRequired': 'Adjunte una foto o imagen del recibo.',
    'receipts.requiredField': 'Campo obligatorio',
    'receipts.invalidAmount': 'Valor inválido',
    'receiptStatus.draft': 'Borrador',
    'receiptStatus.submitted': 'Enviado',
    'receiptStatus.underReview': 'En revisión',
    'receiptStatus.approved': 'Aprobado',
    'receiptStatus.rejected': 'Rechazado',
    'receiptStatus.paid': 'Pagado',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Perfil, controles piloto y preferencias de la app.',
    'settings.preferences': 'Preferencias',
    'settings.language': 'Idioma',
    'settings.languageHelp': 'Elija el idioma de la aplicación.',
    'settings.saved': 'Idioma guardado.',
    'settings.unsavedChanges': 'Cambios sin guardar',
    'settings.unsavedDialogTitle': 'Configuración modificada',
    'settings.unsavedDialogMessage':
        'Tiene cambios de configuración sin guardar. ¿Qué desea hacer antes de salir?',
    'settings.discarded': 'Cambios descartados.',
    'settings.draftRecovered':
        'Hay un borrador de configuración disponible para revisión.',
    'settings.data': 'Datos',
    'settings.account': 'Cuenta',
    'settings.profile': 'Perfil',
    'settings.company': 'Empresa',
    'settings.permissions': 'Permisos',
    'settings.theme': 'Tema',
    'settings.dateFormat': 'Formato de fecha',
    'settings.dateFormatValue': 'MM/DD/AAAA',
    'settings.timeFormat': 'Formato de hora',
    'settings.timeFormatValue': '12 horas',
    'settings.units': 'Unidades',
    'settings.reports': 'Reportes',
    'settings.timesheetFormat': 'Formato del timesheet',
    'settings.paperSize': 'Tamaño del papel',
    'settings.defaultPaperSize': 'Tamaño predeterminado del papel',
    'settings.orientation': 'Orientación',
    'settings.pdfOrientation': 'Orientación del PDF',
    'settings.about': 'Acerca de',
    'settings.version': 'Versión',
    'settings.privacy': 'Privacidad',
    'settings.terms': 'Términos',
    'settings.restoreDefault': 'Restaurar valores predeterminados',
    'settings.landscapePlanned': 'Horizontal planificado',
    'import.title': 'Importación de Obras',
    'import.subtitle':
        'Base local de obras para Field Time. Funciona sin conexión.',
    'import.updateJobs': 'Actualizar obras',
    'import.viewReport': 'Ver reporte',
    'import.lastUpdate': 'Última actualización',
    'import.lastFile': 'Último archivo procesado',
    'import.jobsCount': 'Cantidad de obras',
    'import.errorCount': 'Cantidad de errores',
    'import.processedFile': 'Archivo procesado',
    'import.noSpreadsheet': 'No se encontró ninguna planilla',
    'import.noFileProcessed': 'Ningún archivo procesado',
    'import.pending': 'Pendiente',
    'import.summary': 'Resumen',
    'import.databaseUnavailable': 'Base de obras no disponible',
    'import.loadError':
        'El archivo de obras falta o no es válido. Importe la planilla nuevamente y revise JOBS_IMPORT_REPORT.md.',
    'import.reviewReport': 'Revise el reporte antes de usar la base en campo.',
    'import.updateInstructions':
        'Reemplace la planilla actualizada en data_import/input/ y ejecute dart run tool/import_jobs_from_excel.dart. La carga remota no fue implementada en esta etapa.',
    'import.reportTitle': 'Reporte de Importación',
    'import.reportInstructions':
        'El reporte local se genera en data_import/reports/JOBS_IMPORT_REPORT.md.',
    'approval.approve': 'Aprobar',
    'approval.reject': 'Rechazar',
    'approval.review': 'Revisar',
    'approval.pending': 'Pendiente',
    'approval.approved': 'Aprobado',
    'approval.rejected': 'Rechazado',
    'approval.underReview': 'En revisión',
    'approval.corrected': 'Corregido',
    'approval.resubmitted': 'Reenviado',
    'approval.correctionRequested': 'Corrección solicitada',
    'approval.closed': 'Cerrado',
    'approval.working': 'Trabajando',
    'approval.reason': 'Motivo',
    'approval.observation': 'Observación',
    'approval.confirmation': 'Confirmación',
    'approval.history': 'Historial',
    'approval.approvedBy': 'Aprobado por',
    'approval.rejectedBy': 'Rechazado por',
    'approval.reviewedBy': 'Revisado por',
    'approval.confirmApprove': '¿Aprobar este registro?',
    'approval.confirmReject': '¿Rechazar este registro?',
    'approval.approveMessage':
        'El registro se marcará como Aprobado, quedará bloqueado para ediciones comunes y se liberará para Timesheet y reportes.',
    'approval.rejectMessage':
        'El registro será devuelto al colaborador con el motivo informado.',
    'approval.confirmApproveTitle': 'Confirmar aprobación',
    'approval.approvalObservation': 'Observación de la aprobación',
    'approval.rejectRecord': 'Rechazar registro',
    'approval.rejectionReasonRequired': 'Motivo obligatorio del rechazo',
    'approval.reviewRecord': 'Revisar registro',
    'approval.reviewRequest': 'Corrección o verificación solicitada',
    'approval.additionalObservations': 'Observaciones adicionales',
    'approval.sendToReview': 'Enviar a revisión',
    'approval.reviewEntry': 'Revisar registro',
    'approval.clockIn': 'Entrada',
    'approval.clockOut': 'Salida',
    'approval.breakMinutes': 'Descanso min',
    'approval.travelBonus': 'Travel Bonus',
    'approval.requiredJustification': 'Justificación obligatoria',
    'approval.saveReview': 'Guardar revisión',
    'approval.approveAll': 'Aprobar todos',
    'approval.approveAllValid': 'Aprobar todos los válidos',
    'approval.noSubmittedRecords': 'Sin registros enviados',
    'approval.noSubmittedRecordsHelp':
        'Los registros pendientes de Employee y Contractor aparecen aquí.',
    'supervisor.title': 'Centro del Supervisor',
    'supervisor.management': 'Gestión',
    'supervisor.approveTime': 'Aprobar Horas',
    'supervisor.schedule': 'Programación',
    'supervisor.jobs': 'Obras',
    'supervisor.peopleByJob': 'Equipo por Obra',
    'supervisor.workingNow': 'Trabajando Ahora',
    'supervisor.pilotMode': 'modo piloto',
    'supervisor.managementUnavailable': 'Gestión no disponible',
    'supervisor.clockInSimulated': 'Entrada simulada en el piloto.',
    'supervisor.breakStarted': 'Descanso iniciado en el piloto.',
    'supervisor.breakEnded': 'Descanso finalizado en el piloto.',
    'supervisor.hoursSent': 'Horas enviadas.',
    'supervisor.roleChanged': 'Modo de prueba cambiado.',
    'supervisor.createJobsAllowed':
        'El Supervisor puede registrar obras en el piloto.',
    'supervisor.createJobsBlocked':
        'Registro de obras por Supervisor bloqueado.',
    'supervisor.jobCreated': 'Nueva obra creada en el piloto.',
    'supervisor.jobUpdated': 'Obra actualizada.',
    'supervisor.employeeOrContractorOnly':
        'Solo los perfiles Employee o Contractor registran horas.',
    'supervisor.hoursCorrectedResubmitted':
        'Horas corregidas y reenviadas para aprobación.',
    'supervisor.hoursSentForApproval': 'Horas enviadas para aprobación.',
    'supervisor.correctionReasonRequired': 'Informe el motivo de la solicitud.',
    'supervisor.correctionSent': 'Corrección enviada para nueva revisión.',
    'supervisor.entryApproved': 'Registro aprobado.',
    'supervisor.entryRejected': 'Registro rechazado.',
    'supervisor.entrySentToReview': 'Registro enviado para revisión.',
    'supervisor.approvedRecordLocked':
        'El registro aprobado está bloqueado para ediciones comunes.',
    'supervisor.changeJustificationRequired':
        'Todo cambio requiere una justificación.',
    'supervisor.reviewSavedAudit':
        'Revisión guardada con registro de auditoría.',
    'supervisor.batchApproveJustificationRequired':
        'Informe una justificación para aprobar en lote.',
    'supervisor.validRecordsApproved': 'Registros válidos aprobados.',
    'supervisor.reviewJustificationRequired':
        'Informe la justificación de la revisión.',
    'supervisor.rejectionReasonRequired': 'Informe el motivo del rechazo.',
    'supervisor.permissionDenied':
        'Este perfil no tiene permiso para ejecutar esta acción.',
    'supervisor.noAssignedJob':
        'No hay ninguna obra asignada a este colaborador.',
    'supervisor.testMode': 'Modo de prueba',
    'supervisor.rbacUpdates':
        'La interfaz se actualiza inmediatamente según RBAC.',
    'supervisor.pendingHours': 'Horas pendientes',
    'supervisor.approvedHours': 'Horas aprobadas',
    'supervisor.rejectedHours': 'Horas rechazadas',
    'supervisor.activeJobs': 'Obras activas',
    'supervisor.openClockIns': 'Entradas abiertas',
    'supervisor.reviewSubmittedRecords': 'Revisar registros enviados',
    'supervisor.dailyRoute': 'Ruta diaria del supervisor',
    'supervisor.jobsAndDetails': 'Obras y detalles de obra',
    'supervisor.dailyAllocation': 'Asignación diaria por obra',
    'supervisor.today': 'Hoy',
    'supervisor.week': 'Semana',
    'supervisor.calendar': 'Calendario',
    'supervisor.currentWorkerJob': 'Mi obra de hoy',
    'supervisor.workerJobSubtitle':
        'Mi programación, mis horas y correcciones.',
    'supervisor.noHoursSent': 'Sin horas enviadas',
    'supervisor.noHoursSentHelp':
        'Los registros del perfil actual aparecen aquí.',
    'supervisor.requestCorrection': 'Solicitar corrección',
    'supervisor.correctionReason': 'Motivo de la corrección',
    'supervisor.observation': 'Observación',
    'supervisor.optionalNote': 'Nota opcional',
    'supervisor.employee': 'Empleado',
    'supervisor.contractor': 'Contratista',
    'supervisor.owner': 'Propietario',
    'supervisor.administrator': 'Administrador',
    'supervisor.coordinator': 'Coordinador',
    'supervisor.employeeNote': 'Observación del empleado',
    'supervisor.supervisorNote': 'Observación del supervisor',
    'supervisor.rejectionReason': 'Motivo del rechazo',
    'supervisor.reviewRequest': 'Solicitud de revisión',
    'supervisor.openRoute': 'Abrir ruta',
    'supervisor.client': 'Cliente',
    'supervisor.supervisor': 'Supervisor',
    'supervisor.scheduledToday': 'Programadas hoy',
    'supervisor.hoursToday': 'Horas hoy',
    'supervisor.peopleScheduled': 'Personas programadas',
    'supervisor.peopleWorking': 'Personas trabajando',
    'supervisor.withoutClockIn': 'Sin entrada',
    'supervisor.totalDayHours': 'Total de horas del día',
    'supervisor.peopleScheduledToday': 'Personas programadas hoy',
    'supervisor.peopleWorkingNow': 'Personas trabajando ahora',
    'supervisor.noChanges': 'Sin cambios',
    'supervisor.noChangesHelp': 'Los cambios y aprobaciones aparecen aquí.',
    'supervisor.jobInfo': 'Información',
    'supervisor.summary': 'Resumen',
    'supervisor.peopleToday': 'Personas de Hoy',
    'supervisor.hours': 'Horas',
    'supervisor.history': 'Historial',
    'supervisor.number': 'Número',
    'supervisor.startDate': 'Fecha de inicio',
    'supervisor.scheduledTime': 'Hora prevista',
    'supervisor.editByPermission': 'Editar según permiso',
    'supervisor.visualEditEnabled': 'Edición visual habilitada en el piloto.',
    'supervisor.nobodyWorking': 'Nadie trabajando ahora',
    'supervisor.openEntriesAppear': 'Las entradas abiertas aparecen aquí.',
    'supervisor.viewRecord': 'Ver registro',
    'supervisor.viewJob': 'Ver obra',
    'supervisor.person': 'Persona',
    'supervisor.role': 'Rol',
    'supervisor.assignedBy': 'Asignado por',
    'supervisor.period': 'Período',
    'supervisor.status': 'Estado',
    'supervisor.notes': 'Observaciones',
    'supervisor.job': 'Obra',
    'supervisor.date': 'Fecha',
    'supervisor.clockIn': 'Entrada',
    'supervisor.clockOut': 'Salida',
    'supervisor.openStatus': 'Abierta',
    'supervisor.interval': 'Descanso',
    'supervisor.total': 'Total',
    'jobStatus.planned': 'Planificada',
    'jobStatus.active': 'Activa',
    'jobStatus.paused': 'Pausada',
    'jobStatus.completed': 'Completada',
    'jobStatus.cancelled': 'Cancelada',
    'assignment.scheduled': 'Programado',
    'assignment.working': 'Trabajando',
    'assignment.breakTime': 'En descanso',
    'assignment.finished': 'Finalizado',
    'assignment.noEntry': 'Sin entrada',
    'assignment.absent': 'Ausente',
    'audit.reportTitle': 'Reporte Completo de Auditoría de Idioma',
  },
};
